my:
  greeting: Hello Ramya
  list:
    value: one,two,three

dbValues: "{connection: 'http://---', userName: 'foo', pass:'pass'}"

db:
  connection: "{connection: 'http://---', userName: 'foo', pass:'pass'}"
  host: 127.0.01
  port: 1200

management.endpoints.web.exposure.include: "*"
spring.profiles.active: test